# Ch.04 Naive Bayes

## 4.5.1

In [76]:
import bayes

In [77]:
listOPosts, listClasses = bayes.loadDataSet()

In [78]:
listOPosts

[['my', 'dog', 'has', 'flea', 'problems', 'help', 'please'],
 ['maybe', 'not', 'take', 'him', 'to', 'dog', 'park', 'stupid'],
 ['my', 'dalmation', 'is', 'so', 'cute', 'I', 'love', 'him'],
 ['stop', 'posting', 'stupid', 'worthless', 'garbage'],
 ['mr', 'licks', 'ate', 'my', 'steak', 'how', 'to', 'stop', 'him'],
 ['quit', 'buying', 'worthless', 'dog', 'food', 'stupid']]

In [79]:
listClasses

[0, 1, 0, 1, 0, 1]

In [80]:
myVocabList = bayes.createVocabList(listOPosts)

In [81]:
myVocabList, len(myVocabList)

(['cute',
  'love',
  'help',
  'garbage',
  'quit',
  'I',
  'problems',
  'is',
  'park',
  'stop',
  'flea',
  'dalmation',
  'licks',
  'food',
  'not',
  'him',
  'buying',
  'posting',
  'has',
  'worthless',
  'ate',
  'to',
  'maybe',
  'please',
  'dog',
  'how',
  'stupid',
  'so',
  'take',
  'mr',
  'steak',
  'my'],
 32)

In [82]:
bayes.setOfWords2Vec(myVocabList,listOPosts[0])

[0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1]

In [83]:
0*len(myVocabList)

0

In [84]:
[0]*len(myVocabList)

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0]

In [85]:
myVocabList.index('my')

31

In [86]:
myVocabList.index('dog')

24

In [104]:
from numpy import *

In [105]:
import imp
imp.reload(bayes)

<module 'bayes' from 'bayes.py'>

In [107]:
listOPosts, listClasses = bayes.loadDataSet()

In [108]:
myVocabList = bayes.createVocabList(listOPosts)

In [109]:
trainMat = []

In [110]:
for postinDoc in listOPosts:
    trainMat.append(bayes.setOfWords2Vec(myVocabList, postinDoc))

In [111]:
print trainMat[:]

[[0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1], [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0], [1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1], [0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1], [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0]]


In [112]:
p0V, p1V, pAb = bayes.trainNB0(trainMat, listClasses)

In [113]:
pAb

0.5

In [114]:
p0V

array([0.04166667, 0.04166667, 0.04166667, 0.        , 0.        ,
       0.04166667, 0.04166667, 0.04166667, 0.        , 0.04166667,
       0.04166667, 0.04166667, 0.04166667, 0.        , 0.        ,
       0.08333333, 0.        , 0.        , 0.04166667, 0.        ,
       0.04166667, 0.04166667, 0.        , 0.04166667, 0.04166667,
       0.04166667, 0.        , 0.04166667, 0.        , 0.04166667,
       0.04166667, 0.125     ])

In [115]:
p1V

array([0.        , 0.        , 0.        , 0.05263158, 0.05263158,
       0.        , 0.        , 0.        , 0.05263158, 0.05263158,
       0.        , 0.        , 0.        , 0.05263158, 0.05263158,
       0.05263158, 0.05263158, 0.05263158, 0.        , 0.10526316,
       0.        , 0.05263158, 0.05263158, 0.        , 0.10526316,
       0.        , 0.15789474, 0.        , 0.05263158, 0.        ,
       0.        , 0.        ])

In [116]:
sum(p0V)

0.9999999999999999

In [118]:
sum(p1V)

1.0

### 4.5.3: 두 가지 문제
    1. P(w|c1) 중 하나라도 0이라면 P(c1|w)의 값도 0이다. (w는 word의 set)
    2. 언더플로우
        : p(w|c)의 값은 0과 1사이의 값인데 보통 아주 작은 값이고
        이 값들이 다 곱해지면 아주아주 작은 값이 된다.
 
*해결방법
    1. 모든 단어가 적어도 한 번은 나타났다고 가정한다. (즉, 0이 되지 않게 ayes의 p0Num의 zeros를 ones로 바꾸고, 
                                                        p1Num의 zeros를 ones로 바꾼다. 
                                                        또한, 언더플로우가 생기지 않도록p0Denom과  p1Denom을 
                                                        2.0으로 변경한다. )
    2. 확률 계산시 로그 함수 적용

In [119]:
bayes.testingNB()

['love', 'my', 'dalmation'] classified as:  0
['stupid', 'garbage'] classified as:  1


## 4.5.4 Bag of Wrods

In [124]:
newPost = 'I love my dalmatian my love'
inDoc = newPost.strip().split()

In [125]:
inDoc

['I', 'love', 'my', 'dalmatian', 'my', 'love']

In [126]:
listOPosts, listClasses = bayes.loadDataSet()
myVocabList = bayes.createVocabList(listOPosts)

In [128]:
bayes.setOfWords2Vec(myVocabList,inDoc)

the word: dalmatian is not in my Vocabulary!


[0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1]

In [129]:
bayes.bagOfWords2VecMN(myVocabList,inDoc)

[0,
 2,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 2]

In [130]:
import numpy as np

In [131]:
np.random.permutation(10)

array([6, 9, 1, 0, 7, 4, 3, 2, 5, 8])

In [132]:
np.random.permutation(10)

array([5, 4, 9, 6, 1, 0, 8, 3, 7, 2])

In [143]:
students = np.array(['신','이','박','안','최'])

In [145]:
students[np.random.permutation(len(students))]

array(['\xeb\xb0\x95', '\xec\x95\x88', '\xec\xb5\x9c', '\xec\x8b\xa0',
       '\xec\x9d\xb4'], dtype='|S3')

### 4.6.2 스팸 메일 테스트 실행

In [148]:
bayes.spamTest()

classification error ['experience', 'with', 'biggerpenis', 'today', 'grow', 'inches', 'more', 'the', 'safest', 'most', 'effective', 'methods', 'of_penisen1argement', 'save', 'your', 'time', 'and', 'money', 'bettererections', 'with', 'effective', 'ma1eenhancement', 'products', 'ma1eenhancement', 'supplement', 'trusted', 'millions', 'buy', 'today']
the error rate is:  0.1


In [153]:
bayes.spamTest()

classification error ['yeah', 'ready', 'may', 'not', 'here', 'because', 'jar', 'jar', 'has', 'plane', 'tickets', 'germany', 'for']
classification error ['thought', 'about', 'this', 'and', 'think', 'possible', 'should', 'get', 'another', 'lunch', 'have', 'car', 'now', 'and', 'could', 'come', 'pick', 'you', 'this', 'time', 'does', 'this', 'wednesday', 'work', 'can', 'have', 'signed', 'copy', 'you', 'book']
classification error ['peter', 'with', 'jose', 'out', 'town', 'you', 'want', 'meet', 'once', 'while', 'keep', 'things', 'going', 'and', 'some', 'interesting', 'stuff', 'let', 'know', 'eugene']
classification error ['linkedin', 'kerry', 'haloney', 'requested', 'add', 'you', 'connection', 'linkedin', 'peter', 'like', 'add', 'you', 'professional', 'network', 'linkedin', 'kerry', 'haloney']
the error rate is:  0.4
